import Quiz1 from "./Quiz/Quiz1";
import Quiz2 from "./Quiz/Quiz2";
import Quiz3 from "./Quiz/Quiz3";
import Quiz4 from "./Quiz/Quiz4";
import Quiz5 from './Quiz/Quiz5';
import Quiz6 from './Quiz/Quiz6';
import Quiz7 from './Quiz/Quiz7';
import Quiz8 from './Quiz/Quiz8';
import Quiz9 from './Quiz/Quiz9';
import Quiz10 from './Quiz/Quiz10';
import Results1 from "./Results/Results1";
import Results2 from "./Results/Results2";
import Results3 from "./Results/Results3";
import Results4 from "./Results/Results4";
import Results5 from './Results/Results5';
import Results6 from './Results/Results6'
import Results7 from './Results/Results7'
import Results8 from './Results/Results8'
import Results9 from './Results/Results9'
import Results10 from './Results/Results10'
import LoseScreen1 from "./LoseScreen/LoseScreen1";
import LoseScreen2 from "./LoseScreen/LoseScreen2";
import LoseScreen3 from "./LoseScreen/LoseScreen3";
import LoseScreen4 from "./LoseScreen/LoseScreen4";
import LoseScreen5 from "./LoseScreen/LoseScreen5";
import LoseScreen6 from "./LoseScreen/LoseScreen6";
import LoseScreen7 from "./LoseScreen/LoseScreen7";
import LoseScreen8 from "./LoseScreen/LoseScreen8";
import LoseScreen9 from "./LoseScreen/LoseScreen9";
import LoseScreen10 from "./LoseScreen/LoseScreen10";

export {Quiz1, Quiz2, Quiz3, Quiz4, Quiz5, Quiz6, Quiz7, Quiz8, Quiz9, Quiz10,Results1, Results2, Results3, Results4, Results5, Results6, Results7, Results8, Results9, Results10, LoseScreen1, LoseScreen10,LoseScreen2, LoseScreen3, LoseScreen4, LoseScreen5, LoseScreen6, LoseScreen7, LoseScreen8, LoseScreen9}